export const OPCIONES_TARJETA_REGALO = [
  // PINTA Y DECORA
  {
    id: "pinta-tu-pieza",
    label: "Pinta tu pieza de cerámica — 25€",
    clase: "Pinta tu pieza de cerámica",
    claseId: "pintatupieza",
    subtipo: "",
    tipoTaller: "pinta_y_decora",
    precio: 25,
    rutaReserva: "/reserva-pinta-tu-pieza",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "especial-pinta-tu-pieza",
    label: "Especial pinta tu pieza de cerámica — 35€",
    clase: "Especial pinta tu pieza de cerámica",
    claseId: "especialpintatupieza",
    subtipo: "",
    tipoTaller: "pinta_y_decora",
    precio: 35,
    rutaReserva: "/reserva-especial-pinta-tu-pieza",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },

  // CREAR PIEZAS DESDE CERO - 1 SESIÓN
  {
    id: "crea-tu-pieza-favorita-cuenco-taza",
    label: "Crea tu pieza favorita desde cero — Cuenco o taza — 55€",
    clase: "Crea tu pieza favorita desde cero",
    claseId: "creatupiezafavorita",
    subtipo: "Cuenco o taza",
    tipoPieza: "cuenco_taza",
    tipoTaller: "crear_piezas_desde_cero",
    precio: 55,
    rutaReserva: "/reserva-crea-tu-pieza-favorita",
    requiereMetodo: true,
    requiereTipoPieza: true,
  },
  {
    id: "crea-tu-pieza-favorita-frutero-grande",
    label: "Crea tu pieza favorita desde cero — Frutero / cuenco grande — 65€",
    clase: "Crea tu pieza favorita desde cero",
    claseId: "creatupiezafavorita",
    subtipo: "Frutero / cuenco grande",
    tipoPieza: "frutero_grande",
    tipoTaller: "crear_piezas_desde_cero",
    precio: 65,
    rutaReserva: "/reserva-crea-tu-pieza-favorita",
    requiereMetodo: true,
    requiereTipoPieza: true,
  },
  {
    id: "crea-tu-pieza-favorita-jarron-grande",
    label: "Crea tu pieza favorita desde cero — Jarrón grande — 75€",
    clase: "Crea tu pieza favorita desde cero",
    claseId: "creatupiezafavorita",
    subtipo: "Jarrón grande",
    tipoPieza: "jarron_grande",
    tipoTaller: "crear_piezas_desde_cero",
    precio: 75,
    rutaReserva: "/reserva-crea-tu-pieza-favorita",
    requiereMetodo: true,
    requiereTipoPieza: true,
  },
  {
    id: "crea-tu-brunch-bowl",
    label: "Crea tu brunch bowl — 55€",
    clase: "Crea tu brunch bowl",
    claseId: "creatubrunchbowl",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero",
    precio: 55,
    rutaReserva: "/reserva-crea-tu-brunch-bowl",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "crea-tu-cuenco-ramen",
    label: "Crea tu cuenco para ramen — 55€",
    clase: "Crea tu cuenco para ramen",
    claseId: "creatucuencoramen",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero",
    precio: 55,
    rutaReserva: "/reserva-crea-tu-cuenco-ramen",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "crea-tu-bandeja-hogar",
    label: "Crea tu bandeja de hogar — 55€",
    clase: "Crea tu bandeja de hogar",
    claseId: "creatubandejahogar",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero",
    precio: 55,
    rutaReserva: "/reserva-crea-tu-bandeja-hogar",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "crea-tu-taza-favorita",
    label: "Crea tu taza favorita — 55€",
    clase: "Crea tu taza favorita",
    claseId: "creatutazafavorita",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero",
    precio: 55,
    rutaReserva: "/reserva-crea-tu-taza-favorita",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "crea-tu-maceta",
    label: "Crea tu maceta — 55€",
    clase: "Crea tu maceta",
    claseId: "creatumaceta",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero",
    precio: 55,
    rutaReserva: "/reserva-crea-tu-maceta",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "crea-tu-gran-centro-mesa",
    label: "Crea tu gran centro de mesa — 65€",
    clase: "Crea tu gran centro de mesa",
    claseId: "creatugrancentrodemesa",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero",
    precio: 65,
    rutaReserva: "/reserva-crea-tu-gran-centro-mesa",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "crea-tu-jarra-jarron-grande",
    label: "Crea tu jarra / jarrón grande — 75€",
    clase: "Crea tu jarra / jarrón grande",
    claseId: "creatujarrajarrongrande",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero",
    precio: 75,
    rutaReserva: "/reserva-crea-tu-jarra-jarron-grande",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },

  // CREAR PIEZAS DESDE CERO - 2 SESIONES
  {
    id: "crea-tu-set-matcha",
    label: "Crea tu set de matcha — 60€",
    clase: "Crea tu set de matcha",
    claseId: "setmatcha",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero_dos_sesiones",
    precio: 60,
    rutaReserva: "/reserva-crea-tu-set-matcha",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "crea-tu-set-sake",
    label: "Crea tu set de sake — 60€",
    clase: "Crea tu set de sake",
    claseId: "setsake",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero_dos_sesiones",
    precio: 60,
    rutaReserva: "/reserva-crea-tu-set-sake",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "crea-tu-taza-escultorica",
    label: "Crea tu taza escultórica — 58€",
    clase: "Crea tu taza escultórica",
    claseId: "tazaescultorica",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero_dos_sesiones",
    precio: 58,
    rutaReserva: "/reserva-crea-tu-taza-escultorica",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "crea-tu-maceta-organica",
    label: "Crea tu maceta orgánica — 59€",
    clase: "Crea tu maceta orgánica",
    claseId: "macetaorganica",
    subtipo: "",
    tipoTaller: "crear_piezas_desde_cero_dos_sesiones",
    precio: 59,
    rutaReserva: "/reserva-crea-tu-maceta-organica",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },

  // CURSOS Y BONOS
  {
    id: "modela-a-mano-y-decora",
    label: "Modela a mano y decora tus piezas favoritas — 4 clases — 79€",
    clase: "Modela a mano y decora tus piezas favoritas",
    claseId: "modelamano4clases",
    subtipo: "4 clases",
    tipoTaller: "bono_mensual",
    precio: 79,
    rutaReserva: "/reserva-modela-a-mano-y-decora-tus-piezas-favoritas",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "torno-alfarero-y-decoracion",
    label: "Torno alfarero y decoración — 4 clases — 99€",
    clase: "Torno alfarero y decoración",
    claseId: "tornodecoracion4clases",
    subtipo: "4 clases",
    tipoTaller: "bono_mensual",
    precio: 99,
    rutaReserva: "/reserva-torno-alfarero-y-decoracion",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "torno-alfarero-empezar-desde-cero",
    label: "Torno alfarero empezar desde cero — 4 clases — 120€",
    clase: "Torno alfarero empezar desde cero",
    claseId: "tornodesdecero4clases",
    subtipo: "4 clases",
    tipoTaller: "bono_mensual",
    precio: 120,
    rutaReserva: "/reserva-torno-alfarero-empezar-desde-cero",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
  {
    id: "torno-alfarero-perfecciona",
    label: "Torno alfarero perfecciona lo que ya sabes — 6 clases — 145€",
    clase: "Torno alfarero perfecciona lo que ya sabes",
    claseId: "tornoperfeccionamiento6clases",
    subtipo: "6 clases",
    tipoTaller: "bono_mensual",
    precio: 145,
    rutaReserva: "/reserva-torno-alfarero-perfecciona-lo-que-ya-sabes",
    requiereMetodo: false,
    requiereTipoPieza: false,
  },
];